# Generated by Django 3.2 on 2021-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='poll',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
