# Generated by Django 3.2 on 2021-05-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210505_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='poll',
        ),
    ]
